spring:

  mail:
    host: smtp.naver.com
    port: 465
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      debug: true
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: smtp.naver.com
      smtp:
        starttls:
          enable: true

  datasource:
    url: jdbc:mariadb://${MARIADB_URL}
    username: ${MARIADB_USERNAME}
    password: ${MARIADB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MariaDBDialect

  profiles:
    active: local

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  messages:
    basename: i18n/exception,i18n/validation

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: ${JWT_SECRET}
  max-age:
    access: 1800 #60*30
    refresh: 604800 #60*60*24*7



