spring:

  mail:
    host: smtp.naver.com
    port: 465
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      debug: true
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: smtp.naver.com
      smtp:
        starttls:
          enable: true

  profiles:
    active: local

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: ${JWT_SECRET}



