upload:
  image:
    location: /Users/hankyujang/Desktop/springboot-janghankyu/remind/upload/

stored:
  image:
    location: file:/Users/hankyujang/Desktop/springboot-janghankyu/remind/upload/

spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 100

  redis:
    port: 6379
    host: localhost

elastic:
  ip:
    address: localhost