spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 100

  profiles:
    active: local
    include: secret, email, oauth

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  messages:
    basename: i18n/exception,i18n/validation

  data:
    redis:
      host: localhost
      port: 6379