spring:

  mail:
    host: smtp.naver.com
    port: 465
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      debug: true
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: smtp.naver.com
      smtp:
        starttls:
          enable: true

  profiles:
    active: local

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-minutes : 180
  refresh-token-expiration-minutes : 4320

admin:
  token: eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6IlJPTEVfQURNSU4iLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsIm1lbWJlcklkIjoiMSIsInN1YiI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTcwMzA1MzcyOSwiZXhwIjoxNzAzMDY0NTI5MzR9.t9LPTEYJT-reU7BoHNjVCAsjSvX3kO7PucevsGRNCrc


