stored:
  image:
    location: ${S3_ADDRESS}

spring:
  datasource:
    url: jdbc:mariadb://${MARIADB_URL}
    username: ${MARIADB_USERNAME}
    password: ${MARIADB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MariaDBDialect

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

cloud:
  aws:
    credentials:
      accessKey:  ${S3_ACCESSKEY}
      secretKey:  ${S3_SECRETKEY}
    s3:
      bucket: ${S3_BUCKET}
    region:
      static: ap-northeast-2
  stack:
    auto: false

elastic:
  ip:
    address: ${ELASTIC_IP_ADDRESS}