upload:
  image:
    location: /Users/hankyujang/Desktop/springboot-janghankyu/remind/upload/

stored:
  image:
    location: file:/Users/hankyujang/Desktop/springboot-janghankyu/remind/upload/
spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/spring_board
    username: myuser
    password: mypassword
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MariaDBDialect

  redis:
    port: 6379
    host: localhost

elastic:
  ip:
    address: localhost